version: '3.8'
services:
  eureka-server:
    image: netflixoss/eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  app-network:
    driver: bridge
