server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true