server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # 메모리 기반 H2 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (웹 UI로 데이터베이스 확인 가능)
  jpa:
    hibernate:
      ddl-auto: create # 매번 테이블을 새로 생성
