server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
