server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # 메모리 기반 H2 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (웹 UI로 데이터베이스 확인 가능)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷 설정
        show_sql: true    # SQL 쿼리 로그 출력
    hibernate:
    #ddl-auto: create # 매번 테이블을 새로 생성-삭제
    ddl-auto: update # 기존 테이블 유지
  test:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

order:
  kafka:
    topic:
      payment-request: payment-request
      payment-response: payment-response