server:
  port: 8080

#spring:
#  redis:
#    host: localhost
#    port: 6379
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: http://product-service
#          predicates:
#            - Path=/products/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter:
#                  replenishRate: 10
#                  burstCapacity: 20
